openapi: 3.0.1
info:
  title: Swagger UI Demo
  description: Swagger UI demo by gpcoder.com
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: contact@gpcoder.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Staff
    description: Everything about staff
paths:
  '/staffs/':
    post:
      tags:
        - Staff
      summary: Create new Staff
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
          application/xml:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Create new staff success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: null
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: null
        '400':
          description: Invalid input
        '403':
          description: Forbidden Error
    get:
      tags:
        - Staff
      summary: Find existed staffs by condition(paging, sorting)
      security:
        - BasicAuth: []
      parameters:
        - name: page
          in: query
          description: Number of paging
          required: false
          schema:
            minimum: 0
            type: integer
        - name: perPage
          in: query
          description: Number of object per page
          required: false
          schema:
            minimum: 1
            type: integer
        - name: sortBy
          in: query
          description: Type for sorting
          required: false
          schema:
            type: string
        - name: sortType
          in: query
          description: descending or ascending
          required: false
          schema:
            type: string
        - name: searchedValue
          in: query
          description: searched value
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Found staff
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    example: 1
                  perPage:
                    type: integer
                    example: 2
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        firstName:
                          type: string
                        lastName:
                          type: string
                        createAt:
                          type: object
                        updatedAt:
                          type: object
                      example:
                        - id: 1
                          firstName: Tuan
                          lastName: Minh
                          createAt: "2021-06-10T15:37:24.122193"
                          updatedAt:
                        - id: 2
                          firstName: Tran
                          lastName: Quang
                          createAt: "2021-06-10T15:37:24.122193"
                          updatedAt: "2021-06-10T15:37:24.122193"
            application/xml:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    example: 1
                  perPage:
                    type: integer
                    example: 2
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        firstName:
                          type: string
                        lastName:
                          type: string
                      example:
                        - id: 1
                          firstName: Tuan
                          lastName: Minh
                          createAt: "2021-06-10T15:37:24.122193"
                          updatedAt:
                        - id: 2
                          firstName: Tran
                          lastName: Quang
                          createAt: "2021-06-10T15:37:24.122193"
                          updatedAt: "2021-06-10T15:37:24.122193"

        '400':
          description: Invalid input
          content: {}
        '403':
          description: Forbidden Error

  '/staffs/{id}':
    get:
      tags:
        - Staff
      summary: Find staff by id
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: ID of staff
          required: true
          schema:
            minimum: 1
            type: integer
      responses:
        '200':
          description: Found staff
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: "2021-06-10T15:37:24.678193"
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: "2021-06-10T15:37:24.678193"
        '400':
          description: Invalid input
        '403':
          description: Forbidden Error
    delete:
      tags:
        - Staff
      summary: Delete staff by id
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: ID od staff
          required: true
          schema:
            minimum: 1
            type: integer
      responses:
        '200':
          description: Delete staff success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: null
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: null

        '404':
          description: Not found
        '403':
          description: Forbidden Error
    put:
      tags:
        - Staff
      summary: Update staff by id
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: ID of staff
          required: true
          schema:
            minimum: 1
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
          application/xml:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Update staff success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
                  createAt:
                    type: object
                    example: "2021-06-10T15:37:24.122193"
                  updatedAt:
                    type: object
                    example: "2021-06-10T15:37:24.678193"
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  firstName:
                    type: string
                    example: Tuan
                  lastName:
                    type: string
                    example: Minh
        '404':
          description: Not found
        '403':
          description: Forbidden Error

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
